# Copyright 2018 The PDFium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../pdfium.gni")
import("../../../testing/test.gni")

source_set("edit") {
  sources = [
    "cpdf_creator.cpp",
    "cpdf_creator.h",
    "cpdf_npagetooneexporter.cpp",
    "cpdf_npagetooneexporter.h",
    "cpdf_pagecontentgenerator.cpp",
    "cpdf_pagecontentgenerator.h",
    "cpdf_pagecontentmanager.cpp",
    "cpdf_pagecontentmanager.h",
    "cpdf_pageexporter.cpp",
    "cpdf_pageexporter.h",
    "cpdf_pageorganizer.cpp",
    "cpdf_pageorganizer.h",
    "cpdf_path_redactor.cpp",
    "cpdf_path_redactor.h",
    "cpdf_redaction_mark_sanitizer.cpp",
    "cpdf_redaction_mark_sanitizer.h",
    "cpdf_save_object_reader.cpp",
    "cpdf_save_object_reader.h",
    "cpdf_save_trailer.cpp",
    "cpdf_save_trailer.h",
    "cpdf_stringarchivestream.cpp",
    "cpdf_stringarchivestream.h",
    "cpdf_text_redactor.cpp",
    "cpdf_text_redactor.h",
  ]
  configs += [
    "../../../:pdfium_strict_config",
    "../../../:pdfium_noshorten_config",
  ]
  deps = [
    ":contentstream_write_utils",
    "../../../constants",
    "../../fxcrt",
    "../font",
    "../page",
    "../parser",
  ]
  if (pdf_use_skia) {
    deps += [ "../../../skia" ]
  } else {
    deps += [ "../../../skia:redaction_pathops" ]
  }
  visibility = [ "../../../*" ]
}

source_set("contentstream_write_utils") {
  sources = [
    "cpdf_contentstream_write_utils.cpp",
    "cpdf_contentstream_write_utils.h",
  ]
  configs += [
    "../../../:pdfium_strict_config",
    "../../../:pdfium_noshorten_config",
  ]
  deps = [ "../../fxcrt" ]
}

pdfium_unittest_source_set("unittests") {
  sources = [
    "cpdf_creator_unittest.cpp",
    "cpdf_save_trailer_unittest.cpp",
    "cpdf_npagetooneexporter_unittest.cpp",
    "cpdf_pagecontentgenerator_unittest.cpp",
    "cpdf_path_redactor_unittest.cpp",
    "cpdf_text_redactor_unittest.cpp",
  ]
  deps = [
    ":edit",
    "../../fxge",
    "../font",
    "../page",
    "../page:unit_test_support",
    "../parser",
    "../parser:unit_test_support",
    "../render",
  ]
  pdfium_root_dir = "../../../"

  # TODO(crbug.com/40031409): Fix code that adds exit-time destructors and
  # enable the diagnostic by removing this line.
  configs = [ "//build/config/compiler:no_exit_time_destructors" ]
}

pdfium_embeddertest_source_set("embeddertests") {
  sources = [ "cpdf_creator_embeddertest.cpp" ]
  pdfium_root_dir = "../../../"
}
